---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
          python_version: 3
  fixme:
    enabled: false
  radon:
    enabled: true
    config:
      threshold: "C"
  pep8:
    enabled: false
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.py"
  - "**.md"
  - "**.sh"
exclude_paths: []
