language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install: "pip install -r requirements.txt"
script:
  - python main.py -h
  - python main.py --version
  - python main.py -v --check-syntax examples/tutorial.yaml
  - python main.py -v --check-syntax examples/competition.yaml
  - python main.py -v --check-syntax examples/experiment.yaml
  - python automation/parser.py
notifications:
  email:
    on_success: never
    on_failure: always